### ISSUE TITLE
Support for "multi-users" of same project

### ISSUE THREAD

**Issue by 7kaste** [bestrocker221/aws_distributed_runner#2]
Some places use the project name as reference to create resources, such as when generating the SSH keys. If two people work in the same `project_name` but want to generate different deployments they will get conflicts that a resource with that name already exists.

**Comment by bestrocker221** [comment]
Thanks!
Added calling user in the keypair generation.

Fixed  [here](https://github.com/bestrocker221/aws_distributed_runner/commit/1711fe60c5d2a8108f13ed888cfcfe61ec508418)
